from machine import Pin, Timer
import time

led_onboard = Pin("LED", Pin.OUT)
led1 = Pin(1, Pin.OUT)
led2 = Pin(2, Pin.OUT)
led3 = Pin(3, Pin.OUT)
led4 = Pin(4, Pin.OUT)
led5 = Pin(5, Pin.OUT)
led6 = Pin(6, Pin.OUT)
led7 = Pin(7, Pin.OUT)
led8 = Pin(8, Pin.OUT)

def reset():
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    led6.value(0)
    led7.value(0)
    led8.value(0)
    
def allBlink():
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    led6.value(0)
    led7.value(0)
    led8.value(0)
    time.sleep(1)
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    led6.value(1)
    led7.value(1)
    led8.value(1)
    time.sleep(1)
    
def happy(delay):
    for i in range(2):
        led3.value(1)
        time.sleep(delay)
        led3.value(0)
        led4.value(1)
        time.sleep(delay)
        led4.value(0)
        
def sad(delay):
    for i in range(2):
        led1.value(1)
        led2.value(1)
        time.sleep(delay)
        led1.value(0)
        led2.value(0)
        led3.value(1)
        led4.value(1)
        time.sleep(delay)
        led3.value(0)
        led4.value(0)
        led5.value(1)
        led6.value(1)
        time.sleep(delay)
        led5.value(0)
        led6.value(0)
        led7.value(1)
        led8.value(1)
        time.sleep(delay)
        led7.value(0)
        led8.value(0)
        
def surprise(delay):
    for i in range(2):
        led1.value(1)
        led2.value(1)
        led3.value(1)
        led4.value(1)
        led5.value(1)
        led6.value(1)
        led7.value(1)
        led8.value(1)
        time.sleep(delay)
        led1.value(0)
        led2.value(0)
        led3.value(0)
        led4.value(0)
        led5.value(0)
        led6.value(0)
        led7.value(0)
        led8.value(0)
        time.sleep(delay)

def nervous(delay):
    for i in range(2):
        led1.value(1)
        led3.value(1)
        led5.value(1)
        led7.value(1)
        time.sleep(delay)
        led1.value(0)
        led3.value(0)
        led5.value(0)
        led7.value(0)
        time.sleep(delay)
        led2.value(1)
        led4.value(1)
        led6.value(1)
        led8.value(1)
        time.sleep(delay)
        led2.value(0)
        led4.value(0)
        led6.value(0)
        led8.value(0)
        time.sleep(delay)
        
def fear(delay):
    for i in range(2):
        led1.value(1)
        led2.value(1)
        time.sleep(delay)
        led1.value(0)
        led2.value(0)
        led3.value(1)
        led4.value(1)
        time.sleep(delay)
        led3.value(0)
        led4.value(0)
        led5.value(1)
        led6.value(1)
        time.sleep(delay)
        led5.value(0)
        led6.value(0)
        led7.value(1)
        led8.value(1)
        time.sleep(delay)
        led7.value(0)
        led8.value(0)
        
def anger(delay):
    for i in range(4):
        led3.value(1)
        led4.value(1)
        led5.value(1)
        led6.value(1)
        time.sleep(delay)
        led3.value(0)
        led4.value(0)
        led5.value(0)
        led6.value(0)
        led1.value(1)
        led2.value(1)
        led7.value(1)
        led8.value(1)
        time.sleep(delay)
        led1.value(0)
        led2.value(0)
        led7.value(0)
        led8.value(0)
        
def excitement(delay):
    for i in range(2):
        led1.value(1)
        time.sleep(delay)
        led1.value(0)
        led8.value(1)
        time.sleep(delay)
        led8.value(0)
        led3.value(1)
        time.sleep(delay)
        led3.value(0)
        led6.value(1)
        time.sleep(delay)
        led6.value(0)
        
def disgust(delay):
    for i in range(2):
        led1.value(1)
        time.sleep(delay)
        led1.value(0)
        led3.value(1)
        time.sleep(delay)
        led3.value(0)
        led5.value(1)
        time.sleep(delay)
        led5.value(0)
        led7.value(1)
        time.sleep(delay)
        led7.value(0)
        led8.value(1)
        time.sleep(delay)
        led8.value(0)
        led6.value(1)
        time.sleep(delay)
        led6.value(0)
        led4.value(1)
        time.sleep(delay)
        led4.value(0)
        led2.value(1)
        time.sleep(delay)
        led2.value(0)
    
    
reset()
while(True):
    fear(0.2)
